language: go
sudo: false

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get github.com/mattn/go-runewidth
  - go get github.com/nsf/termbox-go
